### 异常

----

```python
try:
	#需要执行的代码
	num = int(input('请输入整数：'))
except:
	#错误执行的代码
	print('请输入整数')
```



* 根据错误类型捕获异常

  语法：

  ```
  try:
  	#错误执行的代码
  	pass
  except 错误类型1：
  	pass
  except 错误类型2：
  	pass
  except 错误类型3：
  	pass
  ```

  示例代码:

  ```python
  try:
  	num = int(input('输入一个整数:'))
  	result = 8 / num
  	print(result)
  except ZeroDivisionError:
  	print('除0错误')
  except ValueError:
  	print('请输入正确的整数:')
  ```


* 捕获未知异常错误

  ```python
  except Exception as result:
  	print('未知错误 %s' % result)
  	
  # 代码示例
  try:
  	num = int(input('输入一个整数:'))
  	result = 8 / num
  	print(result)
  except ZeroDivisionError:
  	print('除0错误')
  except Exception as result:
  	print('未知错误: %s' % result)
  
  ```


* 异常捕获完整语法

  ```
  try:
  	pass
  except 错误类型1:
  	# 错误1会执行的代码
  	pass
  except 错误类型2:
  	# 错误2 会执行的代码
  	pass
  except 错误类型3:
  	# 错误3 会执行的代码
  	pass
  else:
  	# 没有异常才会执行的代码
  finally:
  	# 无论是否有异常,都会执行的代码
  ```



* 主动抛出异常

  1. 创建一个 Exception 对象
  2. 使用 raise 关键字抛出异常

  ```
  def input_password():
      # 1.提示用户输入密码
      pwd = input("请输入密码：")
      # 2. 判断密码长度 >= 8，返回用户输入的密码
      if len(pwd) >= 8:
          return pwd
      # 3. 如果 密码长度 <8 ,主动抛出异常
      print('抛出异常')
      # 1> 创建异常对象
      ex = Exception("密码长度不够")
      # 2> 抛出异常
      raise ex
  
  # 捕获异常
  try:
  	print(input_password())
  except  Exception as result:
  	print(result)
  ```
